### PR TITLE
fix compressed notifications again (#393)

### PR DESCRIPTION
**Pull request by ashkitten**
please be the last issue lol

### CODE REVIEW

**Comment by ashkitten** [comment]
boop @yipdw for merge

**Comment by yipdw** [comment]
it looks like there's an alignment issue:
screenshot_20180318_215828

**Comment by ashkitten** [comment]
ah interesting. i can't really look now but it's to do with flexbox nonsense. i assume if you set `flex: 0` on `.status__info__icons` it'll work?

**Comment by ashkitten** [comment]
there, fixed (i think) (tested by applying changes manually to dev.glitch.social in the web console)

**Comment by yipdw** [comment]
It looks like there might be another CSS issue on collapsed boosts, lengthy toots, etc.  Here's an example from Firefox 58.0a1:

screenshot_20180319_021056

The collapse handle/indicator is barely visible.  The `.status__info__icons` div seems to overflow the column:

screenshot_20180319_021258

**Comment by ashkitten** [comment]
@yipdw fixed

**Comment by yipdw** [comment]
Thanks! Things look okay to me now.

**Pull request merged**
