### PR TITLE
Fix light theme issues with the favourite modal and some background colors

### LINKED ISSUE #1901: Light theme wrong contrast unusable/inaccessible
### Steps to reproduce the problem

1. Install Glitch-Soc
2. Create account
3. Change to light theme
4. Enable confirmation on favourite and boost
5. Try to reply an answer and see no good hightlighed contrast in the post to reply
6. Try to give favourite and observe mixed dark theme with unreadable text because is dark in light theme

### Expected behaviour

Good contrast to highlight answers and be able to read what I am gonna give favourite

### Actual behaviour

Not highlighted post on reply and unreadable posts while making favourite

### Detailed description

There are 2 errors with light theme which I could observe so far:

* While replying a post, the post is not well highlighted causing a little problem in differenciation (usability)
* While making favourite, the confirmation is unreadable because of the dark background like if dark and light theme got mixed

### Specifications

Latest version

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #1901

### CODE REVIEW

**Comment by EchedeyLR** [comment]
If I read correctly, only the favourite confirmation model is fixed in that pull request.

While replying a post, the cited post used to be a little more grey, being well highlighted.

**Comment by ClearlyClaire** [comment]
Can you post a screenshot? Here, it looks like upstream does, which seems perfectly fine to me contrast-wise.

image

**Comment by EchedeyLR** [comment]
I have no screenshot of previous version sadly, but I remember perfectly the referenced post being more grey or a blue-greyish color, like to highlight that was being cited.

**Comment by ClearlyClaire** [comment]
Alright! glitch-soc's light-theme was basically unmaintained so I replaced it with upstream's, and I don't think I'll be maintaining differences, so I think this is a request that should be done upstream. Thank you for your understanding!

**Pull request merged**
