### PR TITLE
[WiP] Significantly reduce webpacker resource consumption

### PR DESCRIPTION
**Pull request by ThibG**
This should significantly reduce resource consumption when building assets.

This should be tested thoroughly as it's pretty easy to mess things up with webpacker.

I'm also not sure how much sense it makes to have a common pack to the two front-ends: wouldn't it make more sense to have two distinct packs, one for each front-end?

### CODE REVIEW

**Comment by ThibG** [comment]
This seems to work, and *greatly* reduces build time, but the downside is having a huge `core/common.js` containing things that are useless to at least one of the front-ends.

A better alternative might be to have three common chunks, one that is common to both front-ends, and one for each front-end. I am not completely sure how to achieve that yet, but this should be possible.

**Comment by lanodan** [comment]
> I'm also not sure how much sense it makes to have a common pack to the two backends: wouldn't it make more sense to have two distinct packs, one for each backend?

You mean frontend here or what kind of backend are your referring to?

**Comment by ThibG** [comment]
sorry, yes, I meant front-end

**Comment by yipdw** [comment]
I don't have an opinion on the large `core/common.js` file, but I _can_ report that this PR gets the asset precompilation step to complete on my VPS once again.  (I think.  I'm still running migrations -- I'll verify the results soon.)

**Comment by ThibG** [comment]
So there's at least one thing that is done wrong here (but that turns out to be functionally ok for some reason): `core/common` is both the name of a cache-group-generated chunk and of an entry point.

Indeed, I tried to mimic upstream's behavior here, but upstream has no `common` entry point, whereas glitch-soc's theming system has one for core and for each flavour. So that should be fixed in any case.

The huge `core/common` chunk is almost 3M large (upstream's `core` is almost 1M). Because it helps in avoiding some duplication, the real additional cost to the user is closer to 1M of additional data, but that's still useless data I would like to cut down (but I don't know how to).

**Comment by ThibG** [comment]
Closing, as it has important downsides and the glitch-soc's build times have recently greatly improved.

**Pull request closed without merging**
