### PR TITLE
Support customizing the source code GitHub repo

### PR DESCRIPTION
**Pull request by Kay-Faraday**

### CODE REVIEW

**Comment by ProgVal** [comment]
Could you also make it work with non-github repositories?

**Comment by Kay-Faraday** [comment]
I would like to, as all our other code is hosted on a little gitweb CGI interface, however that is less trivial as the current code assumes the path to the issue tracker and assumes that "org/repo" is a shorthand name for the repository.

**Comment by Kay-Faraday** [comment]
I suppose we could make it "REPOSITORY_URL" "ISSUE_TRACKER_URL" and "REPOSITORY_SHORT_NAME" instead?

**Comment by ProgVal** [comment]
Sounds good. You can even leave out `REPOSITORY_SHORT_NAME` and always show the full name (to not give Github a special treatment), or just hardcode the truncation if the hostname is github.com

**Comment by Kay-Faraday** [comment]
Always showing the full name, as in always showing the URL? That sounds 
ugly.

**Comment by ClearlyClaire** [comment]
Oh I'm very surprised we don't already do that :x

Please use `source_url` instead of `repository` to not assume github URLs. Upstream does not need those changes as it's already part of upstream.

**Pull request closed without merging**
