### PR TITLE
i18n: Update Polish translation

### PR DESCRIPTION
**Pull request by m4sk1n**

### CODE REVIEW

**Comment by MightyPork** [comment]
Something about this isn't quite right, the glitch translations were supposed to be in the glitch namespace?

maybe it got messed up on some of the merges :thinking:

**Comment by m4sk1n** [comment]
@MightyPork, I don't know anything about the glitch namespace for translations, any example?

**Comment by MightyPork** [comment]
we have a folder for those custom translations - 

https://github.com/glitch-soc/mastodon/tree/master/app/javascript/glitch/locales

but i'm not 100% sure how/if it works now with the big theme shake-up..

**Comment by m4sk1n** [comment]
ok, thanks, I didn't know about it…

**Pull request closed without merging**
