### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by ClearlyClaire**
## Conflicts

None

## Ported changes

- 285a6919369e2bb1fc968e6e5b557bc62f9e53ca
- 9934949fc4c0a019fc7c7d0e7bdd6e68d496a861
- 78ba12f0bf97aee817eb0ab0d2c582b187033c50
- cea9db5a0bfa0201b082e9f829fb4b3089ac0838
- 0512537eb6722f1d52a690a6e1b22c8d0a99103b
- 5b463454593e1aa3ab3d23446cdf57d606e933d5

## Additional changes

- 9f3c3f5209a1e58b187a685ef0da08078d9c6bb2

### CODE REVIEW

**Comment by Plastikmensch** [comment]
The new column doesn't show local-only toots under "All".
I think it should.

**Comment by ClearlyClaire** [comment]
Ah, I knew I was missing something. The current column does not show local-only posts, but that can be configured.

We could bring back the configuration option for this column, but it would be rather awkward having it apply to all three tabs…

Maybe simply have it labelled “Allow local-only posts in `All` tab” but eh

**Comment by Plastikmensch** [comment]
> Ah, I knew I was missing something. The current column does not show local-only posts, but that can be configured.
> 
> We could bring back the configuration option for this column, but it would be rather awkward having it apply to all three tabs…
> 
> Maybe simply have it labelled “Allow local-only posts in `All` tab” but eh

It does show them under "Local", but yeah I think bringing that option back isn't a good idea.
And the name "All" does imply it shows everything, so I'm for just showing them.
Otherwise I think the chance of people completely missing local-only toots is quite high.

**Comment by ClearlyClaire** [comment]
We initially excluded them from “Federated” (which is replaced by “All”) because people were confused that they were showing up there, so… makes sense to me this would be configurable… maybe the setting should only show up when the “All” tab is selected, but that is awkward as well

**Comment by Plastikmensch** [comment]
> We initially excluded them from “Federated” (which is replaced by “All”) because people were confused that they were showing up there, so… makes sense to me this would be configurable… maybe the setting should only show up when the “All” tab is selected, but that is awkward as well

Sorry, didn't get a notification for your reply for some reason.

True, but I think "Federated" and "All" have different meanings.
I'm usually against removing functionality, but I think it would make sense here, though only showing it when "All" is selected does make sense, but as you said it's awkward.

**Comment by ClearlyClaire** [comment]
Ended up adding it as a (default-on) toggle:
image

**Pull request merged**
