### PR TITLE
[Glitch] Make the column header of toot/thread view look like the others

### PR DESCRIPTION
**Pull request by ThibG**
Port https://github.com/tootsuite/mastodon/pull/10097 to glitch-soc.

### CODE REVIEW

**Comment by ariasuni** [comment]
:heart_eyes:

**Comment by lanodan** [comment]
Not sure if it’s the same in vanilla flavour (currently broken on my instance), but shouldn’t clicking on the header of the profile (and others) scroll the column up?

**Comment by ThibG** [comment]
@lanodan this is indeed the behavior of the other columns, I'll fix that

**Comment by ThibG** [comment]
@RX14 I'm moving the conversation here since glitch-soc is used as a front-end for Pleroma.
As I understand, you used to click repeatedly on the “Back” button to go back to the last “pinnable” column in the history. That wasn't an anticipated use case and to be honest it seems very hackish.
I'm thinking of a new feature that I believe would address your concern: do you think it would make sense to have something like “shift+click” on the “Return” button to go back in the browser history to the last pinnable column? (Or first opened one)

**Comment by RX14** [comment]
@ThibG shift+click on the back button would be nice!

**Pull request merged**
