### PR TITLE
Change i18n-tasks config to consider glitch-soc translation files

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This changes `i18n-tasks` to consider upstream translations as external and unchangeable, and consider our translations for checking and managing.

Also fix issues with the translations.

This only applies to Rails-managed translations.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
`i18n-tasks` does not like us overriding strings, I am not too sure what to do about that…

**Comment by ClearlyClaire** [comment]
Fixed by making `i18n-tasks` consider upstream translations as “external”

**Review by Plastikmensch — APPROVED** [review]
Neat :3

I'm not sure why prettier complains about the changes in `i18n-tasks.yml`, but that can be fixed separately.

Edit: Ah, `external:` should probably be before `read:`

**Comment by ClearlyClaire** [comment]
> Edit: Ah, `external:` should probably be before `read:`

No, that's not why, it wants to split the `['{devise, simple_form, doorkeeper}.*', 'config/locales-glitch/\1.%{locale}.yml']` line into multiple lines, but I'm keeping upstream and i18n-tasks style here

**Comment by Plastikmensch** [comment]
> > Edit: Ah, `external:` should probably be before `read:`
> 
> No, that's not why, it wants to split the `['{devise, simple_form, doorkeeper}.*', 'config/locales-glitch/\1.%{locale}.yml']` line into multiple lines, but I'm keeping upstream and i18n-tasks style here

Ah, okay. Can be ignored then.

**Pull request merged**
