### PR TITLE
Remove status background feature

### PR DESCRIPTION
**Pull request by ClearlyClaire**
I don't think anyone uses this, and I don't think it can be made usable.

### CODE REVIEW

**Comment by jordemort** [comment]
I use it, it works on my instance, unless I'm misunderstanding?

image

I'm not going to cry too much if you remove it but I do use it and it works :)

**Comment by ClearlyClaire** [comment]
Yes, it's this feature! I'm surprised someone actually uses it, given it very significantly impact readability!

I'll keep it around at least a little longer then.

**Comment by ClearlyClaire** [comment]
@MagicLike are you still opposed to this feature being removed? If so, do you mind sharing a bit on how you use it?

**Comment by Fl1pp3d0ff** [comment]
Imagine this feature being used with the old CDE tiled backgrounds... My
eyes,

**Comment by MagicLike** [comment]
> @MagicLike are you still opposed to this feature being removed? If so, do you mind sharing a bit on how you use it?

uhhh I don't even remember opposing to this or even why O.o - I am not using it myself so I don't really care...

I guess something similar to this (with a cleaner integration) could be great to replicate *key's background feature, but the current implementation looks kinda ugly tbh (referring to the screenshot from @jordemort)

**Pull request merged**
