### PR TITLE
Add missing set pack to authorizations_controller

### PR DESCRIPTION
**Pull request by chriswmartin**
same thing as commit 204688e803f76acdfbee833c4d1c0c0a9cc07560 except that it applies styling to oauth/authorize pages

### CODE REVIEW

**Comment by marrus-sh** [comment]
Is this the “X application wants to access your data” page? The `auth` pack might be more appropriate since that page more closely resembles the signin pages.

**Comment by marrus-sh** [comment]
Alternatively, the `modal` pack (which is used for remote follows) might be good. :P idk

(none of these packs actually do anything atm but we distinguish them for forward-compatibility)

**Comment by chriswmartin** [comment]
I used 'settings' because that's the one used in app/controllers/oauth/authorized_applications_controller.rb atm, I can change it to 'auth' if you think that's better though

**Comment by marrus-sh** [comment]
`settings` provides some extra javascripts that we don't need on that page, so `auth` might be a better fit for now, yeah

thanks~

**Pull request merged**
