### PR TITLE
Merge branch 'master' into glitch-soc/merge-upstream

### PR DESCRIPTION
**Pull request by ThibG**
Conflicts:
        app/javascript/mastodon/initial_state.js
        db/schema.rb

Upstream added a new field to initial_state.
Not too sure about what happened with db/schema.rb though…

### CODE REVIEW

**Comment by yipdw** [comment]
The keyword mutes stuff in glitchsoc adds database objects and there was a change that involved altering keyword mute data structures (#454, #531), so that was probably it.  The schema looks intact to me, though.

**Comment by ThibG** [comment]
Yeah, it complained about a conflict in a very weird way, and I fixed it by basically taking upstream's schema version, and was then confused some more by git. But this looks ok.

**Comment by ThibG** [comment]
Everything seems to work, but there is a change breaking compatibility with old Mastodon instances (c3b3594305f4480b02177f4f90d134eb63c8f873)

**Comment by yipdw** [comment]
Hmm, that's probably okay? glitch-soc tends to ride tootsuite/master anyway.

**Pull request merged**
