### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by ThibG**
This merges upstream changes, the main change is switching away from glitch-soc's keyword mutes to upstream's custom filters.

This is done by using both systems in the merge commit, then migrating existing records to upstream's system in a subsequent commit. User-side filters are not implemented for the glitch-soc flavour in this PR.

### CODE REVIEW

**Comment by ThibG** [comment]
Well, CI fails for a reason I don't understand

**Comment by ThibG** [comment]
The CI failure is due to 523d8f20e31e033e375325545bb73f7f59610236 but I'm not sure how to fix that properly.

**Comment by ThibG** [comment]
So… it seems that `travis_wait ./bin/rails parallel:create parallel:load_schema parallel:prepare assets:precompile` somehow runs `yarn install --no-progress --production` (although I can't find why), which used to be a no-op because of the `unless Dir.exist?(…)` thing in the `bin/yarn` wrapper and isn't the case anymore… I guess this install process, with the `--production` flag, uninstalled the dev depencencies (which jest is part of)

**Comment by yipdw** [comment]
Seems okay to me.  I am interested in checking if the glitch keyword mute examples are also satisfied by the mute code in upstream / maintaining some of those checks, but that code doesn't need to be on master for that to happen.

**Comment by ThibG** [comment]
I have added some of those tests upstream, but not all. I can add more of them back if you want.

**Comment by yipdw** [comment]
I must have missed those when looking over the diff (not unusual for me with big diffs). I’ll look for those.

**Comment by ThibG** [comment]
They are part of that commit: https://github.com/glitch-soc/mastodon/pull/557/commits/1ca4e51eb38de6de81cedf3ddcdaa626f1d1c569

**Pull request merged**
