### PR TITLE
Fix travis.yml

### PR DESCRIPTION
**Pull request by ncls7615**
we need this setting?
travis

### CODE REVIEW

**Comment by beatrix-bitrot** [comment]
why remove this? so you can run travis on branches without creating PRs for them?

**Comment by ncls7615** [comment]
travis ci does not work on development branch (example: feature/xxx / fix/xxx) with these settings.

```yaml
-branches:
 -  only:
 -  - master
```

i think this is good for tootsuite/mastodon
but this is not good for other forks imo
if you dont like this changes, i will close this pull request

**Comment by yipdw** [comment]
Oh, the presence of the `branches: only:` block is probably also what's preventing my `merge-upstream` branches from getting a CI run if I don't supply a pull request for those branches.

Having a PR attached to the branch has tracking value, but I can see the PR process (and `branches: only:`) being an extra annoyance for someone who's running their own fork but still wants to benefit from CI runs.  It might make sense to drop this requirement from glitch-soc.

On the other hand, we're not likely to throw .travis.yml into a lot of churn, so it's probably also okay to have forks downstream from glitch-soc make this modification on their own and let git maintain the difference.

**Comment by beatrix-bitrot** [comment]
yeah i was curious of your opinion on this @yipdw

i'm not against merging it 🤷‍♀️

**Pull request merged**
