### PR TITLE
[Glitch] retrieve custom emoji list via API instead of before page load

### PR DESCRIPTION
**Pull request by ThibG**
Port b08ab329f4d149fd414e0539574f49062c571a8a to glitch-soc

### CODE REVIEW

**Comment by Reverite** [comment]
LGTM!

**Comment by yipdw** [comment]
Apologies for the merge delay on some of these -- I like to deploy these changes to get a better understanding of what they do, but my Docker image build workflow was interrupted because I can no longer build on my instance.  (It doesn't have enough memory...)

The Right Way to do that is to build artifacts on a separate machine and then ship them to production systems; I've been slowly getting that pipeline online.  In the meantime, I think you have push access?

**Comment by ThibG** [comment]
Yeah, I can merge this one, I just like to have a second set of eyes on my PRs ;)

**Comment by Reverite** [comment]
@yipdw I push asset building onto [Docker Hub (see step 20)](https://hub.docker.com/r/pluralcafe/mastodon/builds/b3qmhqtxyncs4tymny4gqsa/) but that might not be the most optimal, and it takes ~90% more time to build.

**Pull request merged**
