### PR TITLE
Fix Public TL not indicating new toots when `allowLocalOnly` is enabled

### PR DESCRIPTION
**Pull request by Plastikmensch**
Requires https://github.com/mastodon/mastodon/pull/26247

Same as #2335

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Isn't that at least partially an upstream issue?

**Comment by Plastikmensch** [comment]
> Isn't that at least partially an upstream issue?

Oh right, the `onlyRemote` part is an upstream issue.
I could remove that for now and keep it in a semi-broken state or wait until that part is fixed upstream.
Neither option I'm really happy with though.

**Comment by ClearlyClaire** [comment]
It's fine, can you open a PR or issue upstream, though?

**Review by ClearlyClaire — APPROVED** [review]

**Comment by Plastikmensch** [comment]
> It's fine, can you open a PR or issue upstream, though?

Already did: https://github.com/mastodon/mastodon/pull/26247

**Comment by ClearlyClaire** [comment]
Perfect, thanks!

**Pull request merged**
