### PR TITLE
Add option to choose content-type when authoring toots

### PR DESCRIPTION
**Pull request by ThibG**
Allows Markdown and HTML formatting

~~TODO: Fix auto-linking in Markdown~~

### CODE REVIEW

**Comment by ThibG** [comment]
The backend is greatly inspired by monsterpit's changes, but is (in my opinion) less hackish. There are other important changes:
- it only applies to toots, and not bio or bio fields
- it is only applied when the corresponding content-type is set

The front-end is straight from pleroma's mastodonfe, but it is put behind a local setting because I found the UI to be confusing.

**Comment by ThibG** [comment]
Fixed issues with link auto-detection and Markdown.

Also added a user setting to set the default content-type for use with “legacy” apps:

image

**Comment by Aldarone** [comment]
There's still some issues with autolinking it seems : 

Screenshot_2019-05-13 Ltch fr

**Comment by ThibG** [comment]
Ok this is because `normal_text` is called for `@Luna` and `_@arkham.cafe` separately. I am not completely sure why, as I don't think the `_` actually gets interpreted. Not sure how to work around that either… :/

**Pull request merged**
