### PR TITLE
Merge upstream changes up to 3554c527954441fd924586a49c7d99a89101ac7e

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This one includes many redesigns to the vanilla UI (which were, for the most part, not applied to the glitch flavor yet), as well as a new interaction modal, and a few important bugfixes.

### Postponed changes (recap)

- 59478a1b46e934c75ad27f1270d9b9411de3f185 (UI focus changes, see #2342)
- cfd50f30bb5dda4dd90e1ad01f3e62c99135c36f (UI focus changes, see #2342)
- 4d01d1a1eeef7a851b77def9c5bfc2ce4d7a271c not sure this is a good idea (16:9 cropping changes, see #2346)
- 6b2952d1dd2c21a8a8854f1df5fa532f8fed5af4 too much I dislike in this for now (link previews redesign, see #2343)
- 42992084872a74cfe6be2b56b35cf3d3cfa69c9f follow-up to 6b2952d1dd2c21a8a8854f1df5fa532f8fed5af4 (link previews redesign, see #2343)
- bbea0529354c392f70843860956421e9bc25f2c6 (emoji picker fix, dependent on onboarding changes, see #2200)
- 1e4ccc655acb0ac746656bed891d44b3a986384b (role badges redesign, see #2341)

### Conflicts

- `app/models/account.rb`:
  Upstream added new validations close to lines on which glitch-soc had modified validations to handle custom limits set through environment variables.
  Ported upstream changes.
- `config/initializers/content_security_policy.rb`:
  Upstream added `AZURE_ALIAS_HOST`. Glitch-soc's version of the file is completely different.
  Added `AZURE_ALIAS_HOST` to our version of the file.

### Ported changes

- 4c18928a931c8dc149fa3e0bd7de8ce4f6242715
- 586b1c9dca07c894af4248f59c847e7a3bf6d786

### Conflicts

- `app/views/layouts/application.html.haml`:
  Upstream removed the `crossorigin` attribute from `preload_pack_asset`. Glitch-soc had different calls to `preload_pack_asset` because of the different theming system.
  Ported the change.
- `app/views/layouts/embedded.html.haml`:
  Upstream removed the `crossorigin` attribute from `preload_pack_asset`. Glitch-soc had different calls to `preload_pack_asset` because of the different theming system.
  Ported the change.

### Conflicts

- `config/initializers/content_security_policy.rb`:
  Upstream fixed an issue that was not present in glitch-soc.
  Kept our version.

### Ported changes

- e4ea80d8089110790bf11f7d4021dbe7b6a866de

### Postponed changes

- 59478a1b46e934c75ad27f1270d9b9411de3f185 (UI focus)

### Conflicts

None

### Ported changes

- 217ef7f2aff08575c505368199f059c3c9d79df5

### Postponed changes

- cfd50f30bb5dda4dd90e1ad01f3e62c99135c36f (UI focus)

### Conflicts

- `db/schema.rb`:
  Upstream regenerated the schema file using Rails 7, the conflicts are caused by our extra columns.
  Applied upstream's changes, but keeping our extra columns.

### Ported changes

- 80809ef33efcb80e18ff2193eb6ec30b3bb0fdf7
- 76fce34ebb455d88a34290154ad8f02f582a67c0
- 9a567ec1d1fdb50573c882b7e454285ef7f4200c
- d1a9f601c7eac36f94e91814d3b28ecebaf6ff32
- 714a20697f5e2f7994df012a5a8bbb49bc56f2e7
- 49d2e8979fa43596e992719435117e368ab76254
- ce1f35d7e213327549b960bb64f63c67a141ea40
- f826a95f6e98b36841a87389590a65e79877fc7d

### Postponed changes

- 4d01d1a1eeef7a851b77def9c5bfc2ce4d7a271c not sure this is a good idea (16:9 cropping)
- 6b2952d1dd2c21a8a8854f1df5fa532f8fed5af4 too much I dislike in this for now (link previews redesign)
- 42992084872a74cfe6be2b56b35cf3d3cfa69c9f follow-up to 6b2952d1dd2c21a8a8854f1df5fa532f8fed5af4 (link previews redesign)

### Skipped changes

- 5e8cbb5f82ab0df0de80539650a6e55d7cf7a3a5 disagree with this

### Conflicts

None

### Ported changes

- 6781dc6462b0511a2d3e6e08c965b7006ffd3331
- a4b69bec2eab61f2c3dcebddfe1474be386f828e

### Conflicts

- `app/controllers/authorize_interactions_controller.rb`:
  Small conflict due to our theming system.
- `streaming/index.js`:
  Upstream refactored part of the streaming server. We had some extra logic for handling local-only posts.
  Applied the refactor.

### Additional changes

- a1f1424e76710d1bbc43bf488b7859217507ccce
- 73a3228e0f51041da457ad452608b321b1cb8046

### Ported changes

- b4e739ff0f64c601973762ac986c0e63092d2d7e
- a4ec187a203f52dd2fe0bdeb90e9d950a216b107

### Postponed changes

- bbea0529354c392f70843860956421e9bc25f2c6 (emoji picker fix, dependent on onboarding changes)
- 1e4ccc655acb0ac746656bed891d44b3a986384b (role badges redesign)

### CODE REVIEW

**Comment by Plastikmensch** [comment]
I think some CSS is missing/broken with the new interaction modal:

Screenshot_2023-07-30_18-01-47

**Comment by ClearlyClaire** [comment]
You're right :weary:

Seems like it's using the search popout redesign…

**Comment by Plastikmensch** [comment]
> You're right :weary:
> 
> Seems like it's using the search popout redesign…

In that case merging #2333 first would solve that.
Or it could be postponed.

**Review by Plastikmensch — APPROVED** [review]
GitHub is incredibly unresponsive for me, but everything seems to work.

Not sure I like the interaction modal querying the peers api when it's disabled, but that's an upstream issue. 

Oh wait, the "Take me home" button doesn't seem to do anything.

**Comment by ClearlyClaire** [comment]
> Oh wait, the "Take me home" button doesn't seem to do anything.
> Seems like a script is blocked by CSP.
> Not sure if that's a dev vs prod thing again though.

I'm not able to reproduce this. What's the error?

**Comment by Plastikmensch** [comment]
> I'm not able to reproduce this. What's the error?

```
Refused to load the script 'http://localhost:3000/packs/js/common-bbc7fe25912a9e972eea.js'
because it violates the following Content Security Policy directive: "default-src 'none'".
Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

Refused to load the script 'http://localhost:3000/packs/js/core/remote_interaction_helper-1b9b83882afd9c767fc3.chunk.js'
because it violates the following Content Security Policy directive: "default-src 'none'".
Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.
```

Then it's probably a dev vs prod thing again...

**Comment by ClearlyClaire** [comment]
Ah, this may very well be a dev env thing, unlike upstream we don't set a default CSP in the development environment, so the override will disable everything, and there is no default `script-src` to fall back to.

We may want to reuse upstream's CSP definition at some point…

**Comment by Plastikmensch** [comment]
Sorry, I missed that, but 09ebf7e37c8bdaaf15f02cfec0d117ed55d63dae should've been also applied to `app/javascript/flavours/glitch/features/ui/components/favourite_modal.jsx`

It makes no functional difference and the check-i18n workflow is broken anyway, but I wanted to mention it.

**Comment by Leatherface75** [comment]
Anyone else getting 500 error after latest upstream update?
When i revert back it works as it should again.

**Comment by ClearlyClaire** [comment]
As always, when getting 500 errors, look at `mastodon-web` logs.

**Comment by Leatherface75** [comment]
Tried so see in logs from systemd but didn't find anything useful but i can check again later.

**Comment by ClearlyClaire** [comment]
The most likely reason is that you forgot to run database migrations, but the errors will shed more light! On 500 errors, what you want to look at is `journalctl -u mastodon-web`

**Comment by Leatherface75** [comment]
> The most likely reason is that you forgot to run database migrations, but the errors will shed more light! On 500 errors, what you want to look at is `journalctl -u mastodon-web`

Well if that was needed then you're right that's probably the reason.

I just did this

> bundle install
> yarn install
> RAILS_ENV=production bundle exec rails assets:precompile

**Comment by Leatherface75** [comment]
Ok it seems to work not thanks for the help.

**Pull request merged**
