### PR TITLE
Add regex filter back to firehose

### PR DESCRIPTION
**Pull request by Plastikmensch**
The regex filter will apply to all tabs and not be automatically applied when pinned.
Not ideal, but it at least works.

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
Thank you!
The following should allow it to be kept when pinning the column:
```diff
diff --git a/app/javascript/flavours/glitch/features/firehose/index.jsx b/app/javascript/flavours/glitch/features/firehose/index.jsx
index 02490a21bb..f778fbdbca 100644
--- a/app/javascript/flavours/glitch/features/firehose/index.jsx
+++ b/app/javascript/flavours/glitch/features/firehose/index.jsx
@@ -86,17 +86,17 @@ const Firehose = ({ feedType, multiColumn }) => {
     () => {
       switch(feedType) {
       case 'community':
-        dispatch(addColumn('COMMUNITY', { other: { onlyMedia } }));
+        dispatch(addColumn('COMMUNITY', { other: { onlyMedia }, regex: { body: regex } }));
         break;
       case 'public':
-        dispatch(addColumn('PUBLIC', { other: { onlyMedia, allowLocalOnly } }));
+        dispatch(addColumn('PUBLIC', { other: { onlyMedia, allowLocalOnly }, regex: { body: regex } }));
         break;
       case 'public:remote':
-        dispatch(addColumn('REMOTE', { other: { onlyMedia, onlyRemote: true } }));
+        dispatch(addColumn('REMOTE', { other: { onlyMedia, onlyRemote: true }, regex: { body: regex } }));
         break;
       }
     },
-    [dispatch, onlyMedia, feedType, allowLocalOnly],
+    [dispatch, onlyMedia, feedType, allowLocalOnly, regex],
   );
 
   const handleLoadMore = useCallback(
```

**Comment by Plastikmensch** [comment]
> Thank you! The following should allow it to be kept when pinning the column:

Indeed. Thank you!

**Review by ClearlyClaire — APPROVED** [review]

**Comment by Plastikmensch** [comment]
One thing I didn't account for is that it will reset any regex that was set in the public/local timeline :/

**Comment by ClearlyClaire** [comment]
How so?

**Comment by Plastikmensch** [comment]
The firehose column reads settings from `'firehose'`, but the regex for these columns was saved in `public` and `community`.
So after merging the latest changes when opening the firehose column the regex will be empty.
I don't know if that's also the case when the federated or local timeline was pinned before.

**Comment by ClearlyClaire** [comment]
> The firehose column reads settings from `firehose`, but the regex for these columns was saved in `public` and `community`.
> So after merging the latest changes when opening the firehose column the regex will be empty.

Ah, you're right. Maybe it would make sense to use `public` and `community` values depending on the selected tab? Though that's pretty awkward.

>  I don't know if that's also the case when the federated or local timeline was pinned before.

No, that isn't overridden.

**Comment by Plastikmensch** [comment]
> Ah, you're right. Maybe it would make sense to use `public` and `community` values depending on the selected tab? Though that's pretty awkward.

That would be awkward indeed. Especially since the column settings are shared across tabs.

> > I don't know if that's also the case when the federated or local timeline was pinned before.
> 
> No, that isn't overridden.

Ah, that's good to know. Thanks

**Pull request merged**
