### PR TITLE
Merge with upstream @ e668180044560e28bdc5eef94744c210013efcda

### PR DESCRIPTION
**Pull request by imncls**

### CODE REVIEW

**Comment by beatrix-bitrot** [comment]
thanks @imncls 

i think @yipdw may have a merge ready as well so let's see what they say

**Comment by imncls** [comment]
@beatrix-bitrot no problem~
okay
and this branch is currently running on dev.knzk.me

**Comment by yipdw** [comment]
`.container` seems a bit narrow (it's 700px); I think we need to use the `.container` from `mastodon/about.scss` maybe?
screenshot-2018-2-23 dev knzk me

**Comment by imncls** [comment]
@yipdw oh im sorry
i pushed 2 commits
and now latest commit is currently running on dev.knzk.me
seems fixed

**Comment by imncls** [comment]
@yipdw im sorry
i pushed 4 commits
and latest commit version is currently running on dev.knzk.me
seems fixed

**Comment by imncls** [comment]
these errors on about page

**Comment by yipdw** [comment]
No problem! Things look okay on `dev.knzk.me` to me, so I'll merge this.

**Comment by imncls** [comment]
thanks!

**Pull request merged**
