### PR TITLE
Re-add removed statsd support

### PR DESCRIPTION
**Pull request by gmemstr**
Because glitch-soc is based on Mastodon's main branch, statsd support has been removed in https://github.com/mastodon/mastodon/commit/e49819142f98a94ba44e24aa093815bf74afab05#diff-edece8d1bd75b2b4199f216f1346d4d5a4cec5dce1f2c0c9d0b18fa41be70830. However, this change is not yet part of a tagged release, and there is no replacement that I can see. Since upgrading glitch-soc to address the security patches we've stopped recieving metrics. There is an open issue upstream about adding Prometheus metric support but that's probably a little ways off https://github.com/mastodon/mastodon/issues/8640.

### CODE REVIEW

**Comment by ShadowJonathan** [comment]
There was no talk either on re-adding it, which is a big red flag for me personally.

**Comment by ShadowJonathan** [comment]
Removed in https://github.com/glitch-soc/mastodon/pull/2246 under the following reasoning;

> This also drops statsd support because the code used for it is unmaintained, inefficient, and would prevent moving to Rails 7.

**Comment by jippi** [comment]
👋 Any chance of getting statsd back? Its still around upstream, and I'm currently flying blind with my Datadog + Statsd monitoring - alternatively, are there other options for pulling/pushing telemetry out of Mastodon and sidekiq?

**Comment by ClearlyClaire** [comment]
I re-added it upstream yesterday, this will be available in glitch-soc when I get around porting upstream changes. No promise on when that happens, though, this week has been pretty exhausting.

**Comment by ClearlyClaire** [comment]
Also the plan upstream is to eventually remove `nsa` and statsd for good and replace it with OpenTelemetry and/or Prometheus, but that is not ready yet.

**Comment by jippi** [comment]
OpenTelemetry / OpenMetrics would be fantastic - strongly prefer that over statsd :) 

I went with https://github.com/Strech/sidekiq-prometheus-exporter for now to pull out the sidekiq data I needed

Discovered it via https://github.com/flatcar/flatcar-mastodon/blob/main/monitoring/monitoring-versions.env

**Comment by gmemstr** [comment]
Closing this as it's been brought in from upstream.

**Pull request closed without merging**
