### PR TITLE
Add role badges to WebUI

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Port of https://github.com/mastodon/mastodon/pull/21393 to glitch-soc

image

### CODE REVIEW

**Review by Plastikmensch — APPROVED** [review]
I really like the role badge being under the avatar, but I think it somewhat clashes design-wise with the bot badge if present.
It's not too useful to give bots a role, but I have seen admin accounts with bot labels in the wild before (Whether they have a role or not I can't tell).
But I also don't like the wasted space of the other proposal upstream and while the role badge could also be shown in the header, it looks better as is now and works better with long display names.

**Comment by ClearlyClaire** [comment]
This is how it looks with the bot badge:
image

It's not ideal but it works.

**Comment by Plastikmensch** [comment]
> This is how it looks with the bot badge: image
> 
> It's not ideal but it works.

Yeah, I experimented with displaying the bot badge as an overlay on the avatar, which also makes it possible to show it in timelines, but I think it would clash even more with this.
Another idea would be to move the bot badge to the same place as the role badge, but only one could be shown in that case, which also isn't ideal.
I don't have a good solution for that.

**Comment by jippi** [comment]
Thank you ❤️

**Pull request merged**
