### PR TITLE
Merge upstream changes up to 9a3d047f3e604e581e18346424569e28fc9c5b96

### PR DESCRIPTION
**Pull request by ClearlyClaire**
This one will take a while due to the extensive changes required for upgrading react-router.

### Conflicts

None

### Ported changes

- 1b70d7ed7c0fd3a9fcf028bf76b8c62ac8b3897f

### Conflicts

- `app/javascript/mastodon/features/compose/components/compose_form.jsx`:
  Upstream changed one import, close to a glitch-soc-only import to handle different max character counts.
  Ported upstream's change.

### Ported changes

- 33bd8eccd5ed3b9e87140103cf63cd7aa02c22e2
- 9d45a444f90ca6b939eecb52167fc7f39765c438
- 0ad66175bf59a34b03d9ab2347181548d07089ea

### Conflicts

- `yarn.lock`:
  Caused by a glitch-soc-only dependency (`exif-js`).
  Kept it.

### Ported changes

None

### Conflicts

- `config/initializers/content_security_policy.rb`:
  Upstream changed how asset host CSP directives are used, and glitch-soc has
  a pretty different CSP file.
  It may be worth reconsidering the differences between upstream and glitch-soc 
  but for now, just port the change.

## Merge upstream changes up to fc7734df8d8d53639bf244a2f2f3c39bc2fd12a7

N/A

### Conflicts

None

### Ported changes

- d9503a1965a16328b62ea7bf0bb54e87cbe30d29

### Conflicts

- `config/navigation.rb`:
  Conflict due to glitch-soc having extra navigation items for its theming system.
  Ported upstream changes.

### Ported changes

None

### Conflicts and ported changes

- updated `@rails/ujs` imports

### Additional changes

- 8a131fb7bc32ef338e86cc74719815b12b67128f fix `@rails/ujs` usage
- 3c9c0299c081c15b8e46857b66dbdff6f17fc833 fix `ActiveRecord::Migrator` monkey-patch

### Conflicts

- `.rubocop_todo.yml`:
  glitch-soc had extra ignores.  
  Removed them.

### Ported changes

- 948281070335c61657783702ef7d19e49909bed5
- 15182d1e5e595b21c47b48c5d258f30a0251e753

## Additional ported changes

- 8123e86623e6f94b41131e94b17e84518c98ea47 somehow missed in an earlier merge

## Additional changes

- b19d4eb43d3b717647e3ffa248c853070c5ad2e1 fix HAML linting issues

### Conflicts

- `app/javascript/mastodon/features/compose/components/poll_form.jsx`:
  Upstream changed how icons are handled, including on a line modified by   
  glitch-soc to bump the number of poll options.
  Applied upstream's change, while keeping the increased number of poll
  options.

### Postponed changes

- 134de736dcbc6aa613fd5aec21d983d92d8b0be8 (see #2453)

### Conflicts

- `app/javascript/packs/admin.jsx`:
  Upstream fixed `@rails/ujs` imports.
  Already taken care of in 8a131fb7bc32ef338e86cc74719815b12b67128f
- `app/javascript/packs/public.jsx`:
  Upstream fixed `@rails/ujs` imports.
  Already taken care of in 8a131fb7bc32ef338e86cc74719815b12b67128f

### Ported changes

- cb92cdf9af3ba0e53ed6a27f480a44c45b4d6dc1

### Postponed changes

- f08ca3f04289e3a258e8bff772177c20906930c3 (see #2453)

### Postponed changes

- a4e6fe36cb79b24bf31599222ebb99ceef051414 (see #2453)

### Additional changes

- 36c8570e50f847fd83f13285bd5e0142dbc68368 (fix linting issue)

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
It appears to work, but I'm hitting a Typescript issue I don't understand (tbh the `withOptionalRouter` implementation feels a bit like magic)

**Comment by Plastikmensch** [comment]
I don't really find a "pretty" fix for that, but either using an expect error or using `withRouter` instead of `withOptionalRouter` in `permalink.jsx` works and gets rid of the typeerror.

**Comment by ClearlyClaire** [comment]
> While in simple UI, going to an account page with featured tags, clicking one and then clicking a random other element and the back button navigates back to `/home` instead of `/@user/tagged/Hashtag`
> This also happens with other routes, but doesn't seem to happen in the advanced interface.

I am unable to reproduce this, do you have more information?

Also, I fixed the Typescript issue, the `propTypes` were incorrectly set by the `withOptionalRouter` function.

**Comment by Plastikmensch** [comment]
> > While in simple UI, going to an account page with featured tags, clicking one and then clicking a random other element and the back button navigates back to `/home` instead of `/@user/tagged/Hashtag`
> > This also happens with other routes, but doesn't seem to happen in the advanced interface.
> 
> I am unable to reproduce this, do you have more information?

That's very interesting. Not really, I was able to simplify the steps and maybe my instructions were unclear:
Navigate to `/home` in simple UI
Click on an avatar or display name in the home TL, which changes the URL in the browser bar to `/@account`
Click on Follows or Followers in the account header, which changes the URL to `@account/followers` or `@account/following`
Click the back button in the profile header, which changes the URL back to `/home` instead of `/@account`.

This behaviour both occurs in Firefox and Chromium.
Doing these steps on the main branch, sets the URL to `/@account` when clicking the back button.
I am, as always, running a dev environment though, but I'm not sure how that could make the difference here.
I'm also running `yarn install` when switching between the main branch and the test branch.
I don't see any unusual error in the console.

> Also, I fixed the Typescript issue, the `propTypes` were incorrectly set by the `withOptionalRouter` function.

Yes, it's a good fix and I facepalmed because I didn't think of that.

**Comment by ClearlyClaire** [comment]
Ah, I can reproduce this! Let me try to sort this out

**Comment by ClearlyClaire** [comment]
This is an upstream issue, but I'm not sure where it's coming from.

**Comment by ClearlyClaire** [comment]
There are issues in e.g. the list of pending follow requests. Those will be fixed upstream but unfortunately there is an enormous disruptive commit in the way, so I'll probably cherry-pick the fixes.

**Comment by ClearlyClaire** [comment]
I believe all the identified regressions have been addressed. The big changes I was talking about were also merged, but not ported yet, there was no immediate need to do so after all. They will need to be ported soon, though.

**Pull request merged**
