### PR TITLE
Use real transparency for collapse fade-out

### PR DESCRIPTION
**Pull request by smokku**
This replaces fake transparency (gradient to background color) with real transparency blending to background.
Makes difference when using background image.

Method based on https://stackoverflow.com/a/15624692

### CODE REVIEW

**Comment by Plastikmensch** [comment]
That uh... doesn't seem to work for notifications
Screenshot_2023-02-16_12-53-42

**Comment by smokku** [comment]
Looks fine on light theme.

2023-02-16 13 03 03 chrome pl d4846871b7e9

I will investigate dark-theme.

**Comment by smokku** [comment]
Dark Theme looks good now too.

2023-02-16 13 27 47 chrome pl 5d32b2173d1c

**Comment by Plastikmensch** [comment]
The text color is still a bit off. It's blue-ish instead of the default grey-ish.
Also with CWs.
Screenshot_2023-02-16_13-34-45
Screenshot_2023-02-16_13-33-22

Default for comparison:
Screenshot_2023-02-16_13-35-49
Screenshot_2023-02-16_13-29-57

**Pull request closed without merging**
