### PR TITLE
Add optional hCaptcha support

### LINKED ISSUE #1649: Option for recaptcha(v2) or hcaptcha (PLEASE)
### Pitch

Meow, meow! 

Since I am running mstdn.social we do get quite a lot of new "users" on average per day. Since the most recent update we now can "mass suspend". I have been waiting for that option since we are over run with "non-active" business and spam accounts that where just too much to one by one.. (I did for a loong time)

### Motivation

But after suspending pages and pages of idle bot accounts I wanna ask for a captcha on the signup page.. Optional would be perfect since others perhaps don't want this but we REALLY NEED it so much.. 

The "honeypot" feature does not work at all it seems, if I where to guess 80% or more of all new signups per day are bots. I've come to Glitch for this since I don't think it's gonna get implemented in vanilla and that's okay but I really really hope you can take it into consideration <3 

Thank you!

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #1649

This requires setting `HCAPTCHA_SECRET_KEY` and `HCAPTCHA_SITE_KEY`, then enabling the admin setting at `/admin/settings/edit#form_admin_settings_captcha_enabled`.

image

Subsequently, a hCaptcha widget will be displayed when clicking the confirmation email unless the user has registered through a limited-use invite link.

The Content-Security-Policy headers are altered automatically to allow the third-party hCaptcha scripts on the email page if needed.

Rails session ID is renewed on email confirmation to address concerns about hCaptcha being able to steal it. It can still steal it if the user clicks the confirmation link but does not solve the captcha.

### CODE REVIEW

**Comment by Solsticely** [comment]
\o/

**Comment by ThatOneCalculator** [comment]
Can't wait for this to get in!!!! I love it!!!

**Comment by mstdn** [comment]
Amazing!

**Comment by Gargron** [comment]
May I suggest setting `registrations` to `false` in the instance API? Up until now there was no distinction between the sign-up API being open and registrations on the website being open. If a user selects a glitch-soc server with captcha enabled in our iOS app, the app will lead the user through the sign-up form before erroring out on the final button due to the sign-up API being disabled. This would be a very frustrating experience and reflect badly on Mastodon.

**Comment by mstdn** [comment]
> May I suggest setting `registrations` to `false` in the instance API? Up until now there was no distinction between the sign-up API being open and registrations on the website being open. If a user selects a glitch-soc server with captcha enabled in our iOS app, the app will lead the user through the sign-up form before erroring out on the final button due to the sign-up API being disabled. This would be a very frustrating experience and reflect badly on Mastodon.

But does that mean an instance will show up as "closed signup" on joinmastodon.org? :(

**Comment by ClearlyClaire** [comment]
> May I suggest setting `registrations` to `false` in the instance API? Up until now there was no distinction between the sign-up API being open and registrations on the website being open. If a user selects a glitch-soc server with captcha enabled in our iOS app, the app will lead the user through the sign-up form before erroring out on the final button due to the sign-up API being disabled. This would be a very frustrating experience and reflect badly on Mastodon.

Good point. The current registration API doesn't provide any room for improvement at all :/
Even the XMPP world had built-in support for redirections and arbitrary forms in the XEP that introduced in-band registration, but our API has none of that, so we have no way to signal registrations *are* open but not through apps, or require an extra step from apps.

**Comment by mstdn** [comment]
What about something like this:

- Signup process stays as-is
- After email confirm when the user logs in the first time first sole an "optional" captcha before start using the account or access 

So move the captcha a step further back, this doesn't prevent signups but it does prevent a massive botnet use I guess. I'd rather don't have spam accounts but if they are (sure) to stay idle and don't send out (DM) spam I can live with that and remove it manually 

My worry is all spam accounts are waiting for the time to operate, what I don't know but I'd rather don't want to find out.

Not sure if this makes any difference but it's a thought

**Comment by ClearlyClaire** [comment]
This should indeed be possible. The tradeoffs are:
- you still get a lot of noise from bot registrations, but at least they should (hopefully) stay unconfirmed
- the registration process is a little more awkward
- it's more work to implement this way
- (paranoid, i guess) session cookie management is trickier

On the plus side:
- preserves ability to sign up from apps
- hCaptcha doesn't have access to the registration form

**Comment by mstdn** [comment]
Haha nice! Now I wonder what's the better (technical) solution to this issue? A captcha is not a puurfect solution but since it's optional and against bot attacks only it's worth it

**Comment by Solsticely** [comment]
> So move the captcha a step further back, this doesn't prevent signups but it does prevent a massive botnet use I guess. I'd rather don't have spam accounts but if they are (sure) to stay idle and don't send out (DM) spam I can live with that and remove it manually

two things: maybe i still don't get what you're trying to say but if what you're saying is you're going to disable the accounts that havent gotten verified in a massive spam attack, then iOS users are *still* going to be swept up in confusion & bogus experiences.

and another thing, but maybe i'm just contributing more to the more paranoid side of the argument, i think that's going to make it easier for captcha solving services to get through the block, according to 2captcha, they can solve a recaptcha (wow thats a hard word to type in colemak) in 21 seconds. basic math, blah blah blah, they can solve >2800 recaptcha-equivalent captchas in 24 hours sending requests on only 2 threads.
Exactly how long do you think it's going to take you to remove idle accounts?

**Comment by mstdn** [comment]
> two things: maybe i still don't get what you're trying to say but if what you're saying is you're going to disable the accounts that havent gotten verified in a massive spam attack, then iOS users are _still_ going to be swept up in confusion & bogus experiences.

No, those account will just remain since their first 1. need to verify email to get in 2. solve a captcha before editing profile, post toot, interact :)

> and another thing, but maybe i'm just contributing more to the more paranoid side of the argument, i think that's going to make it easier for captcha solving services to get through the block, according to 2captcha, they can solve a recaptcha (wow thats a hard word to type in colemak) in 21 seconds. basic math, blah blah blah, they can solve >2800 recaptcha-equivalent captchas in 24 hours sending requests on only 2 threads. Exactly how long do you think it's going to take you to remove idle accounts?

That a thing that will always be an issue but at least we make it a lot harder for them. Currently it's just far too easy to setup an automated script via API to create unlimited accounts. With a captcha in between the accounts will still be there maybe but they wont be able to do anything before solving a captcha. This will make it at least a little more expensive for bots aka maybe not worth the effort

**Comment by ClearlyClaire** [comment]
I'm a bit too lazy to implement captcha-on-email confirm right now, Devise's flow isn't easily extensible and it would be much messier and involved than the current PR (but definitely possible), also probably more work to maintain in the future.

I think I'll just turn off the `registrations` flag for now.

**Comment by Solsticely** [comment]
@mstdn OOOOOOOohhhhhhhhhhhhhhh oh that makes sence and its smart :smile: 
somehow i just completely missed the word email in your original message :P

**Comment by ClearlyClaire** [comment]
Toying with this
image

**Comment by mstdn** [comment]
> Toying with this image

w000t! This is puurfect! I love the multiple options in this case, botnets can cause also much expenses in email delivery for confirm, option 1 solves that if it's happening with overwhelming phase. Same applies on Sidekiq jobs, it took us 3 days to clear over 8.6M backlogged jobs for spam account removal from back around Christmas. 

Thank you for your hard work and thinking on this issue!

**Review by ThatOneCalculator — APPROVED** [review]

**Comment by ClearlyClaire** [comment]
Thinking more about it, I think CAPTCHA at email verification, while not ideal, is the most versatile, and having only one option makes settings clearer and maintaining easier.

**Comment by ThatOneCalculator** [comment]
Lets' gooo

**Comment by Solsticely** [comment]
\o/

**Pull request merged**
