### PR TITLE
Merge upstream changes up to 6273416292090b2f6bfda33f070cea325a1759df

### LINKED ISSUE #2405: When OMNIAUTH_ONLY=true the web interface stuck and cannot log in v4.2.0
### Pitch

Hi, several days ago I opened this issue in mastodon and seems like it is not working for glitch version as well.

I have been using glitch version all the time. I am wondering will we fix this bug as well? (I honestly really don't enjoy the PR related to that issue. I would prefer the old log in page even it just has one button)

https://github.com/mastodon/mastodon/issues/26849

### Motivation

https://github.com/mastodon/mastodon/issues/26849

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #2405

### Conflicts

None

### Ported changes

- 548c032dbb90ae9c06b05fc05724c49d0b552fd9

### Conflicts

None

### Ported changes

- d8bdba2f9fdfbb8feccfbe6cf6c42980a2ad5cc3
- 5d20733d8d8d5e4ba7f1f37fd8ee8fc13d6e3ab5

### Postponed changes

- 9d290c23d2665a434c3f78eb5f6a6e2b71a722bd (see #2407)

### Conflicts

None

### Ported changes

- 9c1ef8302abe52f6b41eeafadc1bc30dfa079e18

### Skipped changes

- 398635c0c4987ec44d937e98431ff5dee331ea94 (we have a pretty different design and don't have this issue)

### Conflicts

None

### Ported changes

- 1f141f656dc3fd2b3af5d6edde331bac31bb6526
- f3a2e15f8e0274b5fdf28e3ce062084dc142cb2e
- 91040da871dba71a6eb05cd7ae3ed8b9b255680c
- 9b2bc3d1de301c686208b43a8efef5bc808f8e4e

### Conflicts

- `config/initializers/content_security_policy.rb`:
  Upstream added some code to add the Identity Provider's sign-in endpoint to the `form-action` Content Security Policy directive but our version of the file is pretty different.
  Ported the change.

### Ported changes

- d2cfcdd09efe4914e8956d1b2211114bc7c4179a
- 520b57047403f8819206c938bdc2c93a16ec5f16

### Postponed changes (see #2408)

- bd06c13204b13818cb2d7695d9af25fe813fcdb5
- 0712cc2b99c8feec3a43d6c288781137d9efbe39
- 287520453c30e0d1408699b989bec87b0b4d7ed9

## Merge upstream changes up to b90383d07388fe8513e59a6deb1a2391146c6561 (v4.2.0-rc1)

No conflicts and nothing to port

### Conflicts

- `.github/workflows/build-nightly.yml`:
  Upstream modified this file close to a line modified by glitch-soc to disable the ARMv64 builder (as glitch-soc doesn't have one).
  Ported upstream's changes.
- `.github/workflows/build-releases.yml`:
  Upstream modified this file close to lines changed by glitch-soc to change the Docker image repositories used (only ghcr, and based on the organization's name).
  Ported upstream's changes.

### Ported changes

- 2a4fcc51fd44cab3e837e43e8f8dd84fefb97729

## Additional changes

- 60ecca6acbd7288ccbf4dfcca0280a1a0d1da14d

### CODE REVIEW

**Review by Plastikmensch — APPROVED** [review]
Ah, missed that while triaging but I don't like that 5d20733d8d8d5e4ba7f1f37fd8ee8fc13d6e3ab5
also changes the background for the notification bar and tabs on account pages:

Before:
Notification filter bar using darker background
Profile page tabs using darker background

After:
Notification filter bar using same background as other elements
Profile page tabs use same background as other elements

I can't tell if that's an oversight or on purpose though, it just looks off to me.

Just wanted to note that, otherwise the changes look good to me.

**Comment by ClearlyClaire** [comment]
This is a change made on purpose upstream, but I do agree this makes tabs more difficult to visually distinguish from the contents.

**Comment by ClearlyClaire** [comment]
Reverted the background color

**Comment by Plastikmensch** [comment]
Thank you!

**Comment by Plastikmensch** [comment]
Ah, sorry, I usually don't check locales, but upstream has removed `suggestions.dismiss`, but it is still used in `app/javascript/flavours/glitch/features/directory/components/account_card.jsx` to dismiss account suggestions in explore.

**Pull request merged**
