### PR TITLE
i18n: Add translate and fix problems

### PR DESCRIPTION
**Pull request by ncls7615**

### CODE REVIEW

**Comment by ncls7615** [comment]
"mobile" translate is not worked
so i changed layout translate
image
and i added some translate for direct timeline

**Comment by dexamphetamine** [comment]
when you say "mobile" translate doesn't work, do you mean that there was a technical problem or a style problem?

otherwise looks good!

**Comment by ncls7615** [comment]
fixed conflict and some problems

**Comment by dexamphetamine** [comment]
何度もすみませんが、このPRの目的をまだ掴んでいません。つまり、「モバイル」の和訳が間違っていて、いっそう英文字にすべき、ですか？

**Comment by ncls7615** [comment]
> when you say "mobile" translate doesn't work, do you mean that there was a technical problem or a wording/style problem?

i meant technical and style problem
and i added some translate for direct timeline

**Pull request merged**
