### PR TITLE
Move URLs to backend in their own file

### PR DESCRIPTION
**Pull request by ThibG**
cc @lanodan

### CODE REVIEW

**Comment by lanodan** [comment]
Neat.

So for pleroma backend it would just be a change to ``app/javascript/flavours/glitch/util/backend_links.js`` ?

**Comment by ThibG** [comment]
> So for pleroma backend it would just be a change to `app/javascript/flavours/glitch/util/backend_links.js` ?

Yeah that was the aim.

Oh I didn't see that you stripped away reports and added an item to re-use the delete API hm… I'm not sure how to do that cleanly :/

**Comment by lanodan** [comment]
For the Delete API maybe you could pick the previously mentioned commit and put it into glitch-soc?

For the Report it could be considered a temporary pleroma thing, we don’t support reports/``Flag`` right now but might do later, specially as the more detailed API documentation helps there.

**Comment by ThibG** [comment]
Sorry I haven't made progress on this lately. I'm not 100% sure about merging the aforementioned commit as we don't make use of that, but… why not I guess, if that makes things easier down the road.

Do you still think such a PR would be useful?

**Pull request merged**
