### PR TITLE
Sync with upstream @ v1.6.0rc3

### PR DESCRIPTION
**Pull request by yipdw**
This contains all conflict markers from the merge.  They'll be eliminated one at a time; I think this'll help with conflict resolution review.  When we're happy with the resolution, I'll capture the diff, re-run this merge, apply the approved diff, and we'll just have a single merge commit.
    

Resolution TODO:
- [x] both modified:   app/javascript/mastodon/components/status_list.js 2c079ea20fa5a7cfec66d51c1bd6967be9f05482
- [x] both modified:   app/javascript/mastodon/features/notifications/index.js beb357567610c55882b8b8ba71f1a205852fdc06
- [x] both modified:   app/javascript/mastodon/features/ui/components/modal_root.js  06bdb1f03aa261d1727d53be3683bb8c7b7fae5a 
- [x] both modified:   app/javascript/mastodon/features/ui/components/onboarding_modal.js dfb31af445905b971995fd6e0356f427fa880ec3
- [x] both modified:   app/javascript/mastodon/features/ui/index.js 8233c14bceb58f4dd70f1ae82b2264382986676f
- [x] both modified:   app/javascript/styles/about.scss (*)
- [x] both modified:   app/javascript/styles/accounts.scss (*)
- [x] both modified:   app/javascript/styles/components.scss f184a4222156accfa4200d2d853d3edc32810bb6
- [x] both modified:   app/presenters/instance_presenter.rb 84281badfd94ac6fc69eceb9ee1ecf065a018bf3
- [x] both modified:   app/services/post_status_service.rb 457c5879463e8bff25b96e15f23c7e41f05c3472
- [x] both modified:   app/services/reblog_service.rb 4296ba484b77586cef9ba4df06bbe9eb98bc19d0
- [x] both modified:   app/views/about/more.html.haml bb246465ee01a15235ac1ee73c8000ac4a755cc6
- [x] both modified:   app/views/about/show.html.haml 9e2254accbb11191b1e6b3f8d77015d1b427ad8a
- [x] both modified:   app/views/accounts/_header.html.haml dcf9a6feee8b10064566ca12851f122e841b8b3a
- [x] both modified:   config/webpack/loaders/babel.js e148f5b850aea51d7024fa865f40d8b3e6827e5a
- [x] both modified:   spec/controllers/api/v1/accounts/credentials_controller_spec.rb c5b9902557936d927bc2e54854ab3f15278b8e5e

### CODE REVIEW

**Comment by yipdw** [comment]
I think I'd like to have someone else look at the SCSS conflicts: @marrus-sh? @MightyPork? They seem pretty complex to me, but I'm also not yet up to speed with what's changed there and what we want to keep.

**Comment by yipdw** [comment]
The merge has been done, but loading the frontend fails with the following error:

```
17:39:37.512 ReferenceError: classNames is not defined
Stack trace:
render@webpack-internal:///622:221:9
_renderValidatedComponentWithoutOwnerOrContext/renderedElement<@webpack-internal:///403:795:16
measureLifeCyclePerf@webpack-internal:///403:75:12
_renderValidatedComponentWithoutOwnerOrContext@webpack-internal:///403:794:25
_renderValidatedComponent@webpack-internal:///403:821:27
performInitialMount@webpack-internal:///403:361:25
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
performInitialMount@webpack-internal:///403:370:18
mountComponent@webpack-internal:///403:257:16
mountComponent@webpack-internal:///39:45:18
mountComponentIntoNode@webpack-internal:///180:104:16
perform@webpack-internal:///57:143:13
batchedMountComponentIntoNode@webpack-internal:///180:126:3
perform@webpack-internal:///57:143:13
batchedUpdates@webpack-internal:///415:62:14
batchedUpdates@webpack-internal:///23:97:10
_renderNewRootComponent@webpack-internal:///180:319:5
_renderSubtreeIntoContainer@webpack-internal:///180:401:21
render@webpack-internal:///180:422:12
main/<@webpack-internal:///617:47:5
ready@webpack-internal:///222:7:5
main@webpack-internal:///617:43:3
@webpack-internal:///798:17:3
 1 798:19:3
	<anonymous> webpack-internal:///798:19:3
```

**Comment by marrus-sh** [comment]
"classNames is not defined" suggests that there's an `import classNames from "classnames"` statement that was erroneously deleted during the merge? that's my best guess anyway.

**Comment by marrus-sh** [comment]
(also worth noting: glitch always uses `classNames` but upstream has been known to also use the lowercase form, `classnames`. so it's possible that the import statement is using the incorrect casing.)

**Pull request merged**
