### PR TITLE
Fix glitch local settings navigation items not being proper buttons

### PR DESCRIPTION
**Pull request by ClearlyClaire**

### CODE REVIEW

**Review by Plastikmensch — APPROVED** [review]
Not a regression, but worth noting that the CW icon is on the wrong side in RTL.
App settings navigation showing the CW icon being left of the text but it should be right

**Comment by ClearlyClaire** [comment]
Good catch, I'll try to fix that

**Comment by ClearlyClaire** [comment]
Not managing to do it so far

**Comment by Plastikmensch** [comment]
> Not managing to do it so far

It seems adding `unicode-bidi: embed` to `.text-icon-button` in `app/javascript/flavours/glitch/styles/components/local_settings.scss` works.

**Comment by ClearlyClaire** [comment]
Perfect! Can you open a PR for that?

**Comment by Plastikmensch** [comment]
> Perfect! Can you open a PR for that?

Sure!

**Pull request merged**
