### PR TITLE
Fix admin dashboard hashtag link

### PR DESCRIPTION
**Pull request by tribela**
All hashtag links were /admin/hashtag/undefined

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
This doesn't fix anything, does it? Also AFAIK the correct fix would be something like https://github.com/mastodon/mastodon/pull/18943

**Comment by tribela** [comment]
Oh, the real problem was `hashtag.id` is always `undefined` because `api/v1/admin/trends/tags` returns like this:
```json
[
  {
    "name": "CuratorPrompts",
    "url": "https://qdon.space/tags/CuratorPrompts",
    "history": [
      {
        "day": "1672704000",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672617600",
        "accounts": "10",
        "uses": "10"
      },
      {
        "day": "1672531200",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672444800",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672358400",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672272000",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672185600",
        "accounts": "1",
        "uses": "1"
      }
    ],
    "following": false
  },
  {
    "name": "fediverse",
    "url": "https://qdon.space/tags/fediverse",
    "history": [
      {
        "day": "1672704000",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672617600",
        "accounts": "15",
        "uses": "17"
      },
      {
        "day": "1672531200",
        "accounts": "3",
        "uses": "3"
      },
      {
        "day": "1672444800",
        "accounts": "7",
        "uses": "7"
      },
      {
        "day": "1672358400",
        "accounts": "10",
        "uses": "12"
      },
      {
        "day": "1672272000",
        "accounts": "13",
        "uses": "15"
      },
      {
        "day": "1672185600",
        "accounts": "9",
        "uses": "9"
      }
    ],
    "following": false
  },
  {
    "name": "curatorprompts133",
    "url": "https://qdon.space/tags/curatorprompts133",
    "history": [
      {
        "day": "1672704000",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672617600",
        "accounts": "7",
        "uses": "7"
      },
      {
        "day": "1672531200",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672444800",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672358400",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672272000",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672185600",
        "accounts": "0",
        "uses": "0"
      }
    ],
    "following": false
  },
  {
    "name": "sketch",
    "url": "https://qdon.space/tags/sketch",
    "history": [
      {
        "day": "1672704000",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672617600",
        "accounts": "5",
        "uses": "5"
      },
      {
        "day": "1672531200",
        "accounts": "1",
        "uses": "1"
      },
      {
        "day": "1672444800",
        "accounts": "3",
        "uses": "3"
      },
      {
        "day": "1672358400",
        "accounts": "3",
        "uses": "3"
      },
      {
        "day": "1672272000",
        "accounts": "3",
        "uses": "3"
      },
      {
        "day": "1672185600",
        "accounts": "1",
        "uses": "1"
      }
    ],
    "following": false
  },
  {
    "name": "autism",
    "url": "https://qdon.space/tags/autism",
    "history": [
      {
        "day": "1672704000",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672617600",
        "accounts": "5",
        "uses": "7"
      },
      {
        "day": "1672531200",
        "accounts": "1",
        "uses": "43"
      },
      {
        "day": "1672444800",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672358400",
        "accounts": "1",
        "uses": "1"
      },
      {
        "day": "1672272000",
        "accounts": "0",
        "uses": "0"
      },
      {
        "day": "1672185600",
        "accounts": "3",
        "uses": "4"
      }
    ],
    "following": false
  },
  {
    "name": "art",
    "url": "https://qdon.space/tags/art",
    "history": [
      {
        "day": "1672704000",
        "accounts": "3",
        "uses": "4"
      },
      {
        "day": "1672617600",
        "accounts": "25",
        "uses": "35"
      },
      {
        "day": "1672531200",
        "accounts": "15",
        "uses": "19"
      },
      {
        "day": "1672444800",
        "accounts": "33",
        "uses": "41"
      },
      {
        "day": "1672358400",
        "accounts": "50",
        "uses": "82"
      },
      {
        "day": "1672272000",
        "accounts": "32",
        "uses": "40"
      },
      {
        "day": "1672185600",
        "accounts": "37",
        "uses": "48"
      }
    ],
    "following": false
  },
  {
    "name": "books",
    "url": "https://qdon.space/tags/books",
    "history": [
      {
        "day": "1672704000",
        "accounts": "1",
        "uses": "1"
      },
      {
        "day": "1672617600",
        "accounts": "9",
        "uses": "9"
      },
      {
        "day": "1672531200",
        "accounts": "4",
        "uses": "4"
      },
      {
        "day": "1672444800",
        "accounts": "6",
        "uses": "11"
      },
      {
        "day": "1672358400",
        "accounts": "10",
        "uses": "11"
      },
      {
        "day": "1672272000",
        "accounts": "6",
        "uses": "7"
      },
      {
        "day": "1672185600",
        "accounts": "12",
        "uses": "12"
      }
    ],
    "following": false
  }
]

```

**Comment by ClearlyClaire** [comment]
Yeah, because it doesn't use the serializer that it was initially supposed to. Should we close this?

**Comment by Plastikmensch** [comment]
> Yeah, because it doesn't use the serializer that it was initially supposed to. Should we close this?

This can be closed as #2087 merged the fix for the wrong serializer being used.

**Pull request closed without merging**
