### PR TITLE
Initial @twitter.com support from cybrespace

### PR DESCRIPTION
**Pull request by imncls**
| Cybrespace | Glitch-soc |
| :--: | :--: |
|  |  |

i like the simple design

### CODE REVIEW

**Comment by chr-1x** [comment]
fwiw here's the discussion i had about the visual design of this feature way back when i implemented it: https://cybre.space/@chr/98970487302384754

**Comment by imncls** [comment]
@chr-1x thats really interesting discussion
now only displaying it, but i'd like to add "follow twitter peoples" feature in the future
(but, this is just "see the tweets" feature, probably we can not like and retweet them)

**Comment by yipdw** [comment]
@imncls I think consensus is that glitch-soc would be happy to merge this if the `@twitter.com` portion were displayed, just like it is on cybrespace.  (@beatrix-bitrot etc feel free to chime in if you want)

**Comment by imncls** [comment]
@yipdw closing it once, improve it and send pr again!

**Comment by yipdw** [comment]
Oh, you don't have to close it to modify it :) That works too, though.

**Comment by imncls** [comment]
yeah i know :3

**Pull request closed without merging**
