### PR TITLE
[WIP] Merge upstream

### PR DESCRIPTION
**Pull request by yipdw**
This seems to run in dev, so I'm waiting for Travis to check this; if that passes, I'll probably do a test deploy on my instance to catch more odd stuff.

- [X] Quick check in dev
- [x] Travis is green
- [x] Try a limited deployment
- [x] Fix "A look inside" header height

### CODE REVIEW

**Comment by beatrix-bitrot** [comment]
👀

**Comment by yipdw** [comment]
A note: If you don't have `OTP_SECRET` set, the app servers under this branch won't boot.  This is probably not a problem in production, but my development environment was missing that setting.

**Comment by beatrix-bitrot** [comment]
mm yeah i think it's ok?

**Comment by yipdw** [comment]
The timeline preview header is too small when using the `glitch` flavour:

screenshot_20180303_105618

It looks like there's a missing `<button>` in the header.  The glitchsoc `TimelineComponent` doesn't add a `<button>`, so that's probably why.

I'm aware of two instances using glitchsoc that show a public timeline, so this is something that we should probably fix.

**Comment by yipdw** [comment]
>  The glitchsoc TimelineContainer doesn't add a <button>, so that's probably why.

Actually I just realized that this shouldn't matter: it renders fine in the web UI, so it should also work here? Maybe there's a missing `use_pack`.

**Comment by yipdw** [comment]
Header height fixed in 65e2a4645e086110072efed5b3d4d1434c933e04.  It wasn't a pack issue, just conflicting CSS properties.

**Pull request merged**
