### PR TITLE
Run keyword mutes on hashtags

### LINKED ISSUE #207: Apply keyword mutes to #hashtags
Hashtags are expanded in the status text as `<a href="..." rel="...">#<span>hashtag</span></a>`, or something to that effect.  This means that a text match for `#hashtag` will not succeed.  (`hashtag` does, though.)

The keyword mute filter should examine a status' tags.  `#hashtag` and `hashtag` should both match `#hashtag`.

### PR DESCRIPTION
**Pull request by yipdw**
Closes #207.

### CODE REVIEW

**Comment by beatrix-bitrot** [comment]
is this still WIP? what's up?

**Comment by yipdw** [comment]
Still WIP, I've been going between other projects.  I'd like to get back to it soon, though.

**Comment by yipdw** [comment]
The holdup, I guess, is making sure that we have a way to make `#foo` match the hashtag `foo`: not too difficult, just stuff that needs to be written.  (It's likely to be entered as `#foo` in the UI.)

**Comment by yipdw** [comment]
Oops, this pull request is from my personal fork to glitch-soc.  I'll fix that.

**Comment by yipdw** [comment]
This seems to work on my development instance; tests pass also.

With the changes in this PR, it's possible to supply a keyword as `#thing`.  This will mute all hashtags matching `#thing` (but will not match e.g. `#thingiverse`).

You can also supply a non-whole-word match like `oat`, which will match `#oat` and `#oatmeal`.

**Comment by yipdw** [comment]
Come to think of it, the above assertions should be backed up by some examples.  I'll add those.

In the meantime, I think the rest of the code changes can be reviewed.

**Pull request merged**
