### PR TITLE
Add exclusive lists to glitch

### LINKED ISSUE #1204: Feature request: exclusive lists
### Pitch

[Hometown](https://github.com/hometown-fork/hometown), another Mastodon fork, recently released their v1.0 with a neat feature: exclusive lists. This lets you follow someone without their posts appearing in your home feed, only in lists.

### Motivation

Copying from the [Hometown wiki](https://github.com/hometown-fork/hometown/wiki/Exclusive-lists):

> Right now if you add an account to your "friends I like" list in Mastodon, posts from people on that list appear on that list. But they also appear on your home timeline, and maybe you don't want that! Perhaps you'd rather treat your "friends I like" list as your "real" home timeline, and then check your home timeline when you're bored. You can do that with exclusive lists!

### PR DESCRIPTION
**Pull request by Plastikmensch**
Closes #1204
Ref #1293

Updated port of hometowns [exclusive lists feature](https://github.com/hometown-fork/hometown/wiki/Exclusive-lists).
Basically, if you add a user to an exclusive lists, toots from them don't appear in home anymore.

I think this is a useful feature, especially for people who follow a lot of accounts and have an unusable home tl.
There is a PR upstream, but due to upstreams reluctance to add new features despite popular interest, the chances of it being merged are very low.
Glitch would benefit from this feature though.

I have been running this on my custom fork without any issues so far and the feature itself has been proven by hometown.

### CODE REVIEW

**Comment by Plastikmensch** [comment]
Uh-oh I forgot to add `isExclusive` to props in the render function in `glitch/features/list_editor/components/edit_list_form.js`

Also seeing some other issues, I'm on it.

**Comment by Plastikmensch** [comment]
It's working now.
Good thing I decided to look over it another time.

**Comment by vivlim** [comment]
Is clicking this checkmark button after toggling Exclusive mode required to save it?
image

That button is labelled "Change title" which is a bit confusing. It does light up after I toggle "Exclusive?" which seems to indicate that I *do* need to click it.

Also the label "Exclusive?" isn't particularly self explanatory. I think it might be better to give the toggle an entire row, then the label can be more descriptive. Here's a mockup I threw together:
image

**Comment by Plastikmensch** [comment]
> Is clicking this checkmark button after toggling Exclusive mode required to save it? 
> That button is labelled "Change title" which is a bit confusing. It does light up after I toggle "Exclusive?" which seems to indicate that I _do_ need to click it.

Yes, you need to click it, as it's more of a "save changes" button. I agree the "change title" label is misleading, but the label is read from vanilla locales and changing them is up to upstream.
It could be replaced by a glitch locale though. I'll think about that.

> Also the label "Exclusive?" isn't particularly self explanatory. I think it might be better to give the toggle an entire row, then the label can be more descriptive. 

I agree and that has also been brought up on the upstream PR.
Ideally I would move the toggle, so it's not in the list editor, but at the same place where the reply policy setting is.
Sadly I tried that already and couldn't get it to work.
I really like the idea of giving it an entire row though.
Thanks for the feedback!

**Comment by Plastikmensch** [comment]
My CSS skills are awful though:
Screenshot_2022-12-17_12-51-25

**Comment by Plastikmensch** [comment]
I'm a bit torn on this. I got it to work as a column setting, but I'm not sure that's the right place. I'm also not too happy about it being in the list editor, as it's less accessible there.

**Comment by ClearlyClaire** [comment]
Note that upstream is interested in this, and there exists a similar PR there, though I haven't got around to reviewing it yet.

**Comment by Plastikmensch** [comment]
> Note that upstream is interested in this, and there exists a similar PR there, though I haven't got around to reviewing it yet.

Are they actually?
I saw this requested multiple times with a lot of interest of users, but not for actually implementing it.

**Comment by ClearlyClaire** [comment]
https://www.reddit.com/r/Mastodon/comments/zqfr4h/comment/j124ss5/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by Plastikmensch** [comment]
> https://www.reddit.com/r/Mastodon/comments/zqfr4h/comment/j124ss5/?utm_source=reddit&utm_medium=web2x&context=3

Thanks!
Should I close this then?

**Comment by ClearlyClaire** [comment]
Yeah, I think so. Thank you for your contribution though!

**Pull request closed without merging**
