### PR TITLE
Added "joined at" feature

### PR DESCRIPTION
**Pull request by yuzulabo**
74c4112d38c18fdaf164f3a2de9ac81d

### CODE REVIEW

**Comment by yipdw** [comment]
Can we make this a user setting, perhaps something editable under Preferences > Edit profile?

**Comment by marrus-sh** [comment]
A couple comments:

1. This should only be shown for local users since the date will be wrong for non-local ones (it's the date the instance found out about the user, not the date that they joined).
2. Since we're only concerning ourselves with local users, adding a setting for this in preferences isn't out-of-the-picture (note that it wouldn't federate though); I'm not sure about the implementation specifics for that though

**Comment by ncls7615** [comment]
yuzulabo is not good at english
so, i translate comment for him

this is a local only feature.
and difficulty adding setting to the app settings...
sorry.
should i close this?

**Comment by marrus-sh** [comment]
I like this idea and I think some other people have expressed interest
We might want to add some additional functionality before it gets merged though

**Comment by beatrix-bitrot** [comment]
thanks for submitting but it doesn't quite fit for now!

**Comment by yuzulabo** [comment]
I'm sorry...
Thank you for responding.

**Comment by beatrix-bitrot** [comment]
no need to apologize. thanks for your efforts!

**Pull request closed without merging**
