### PR TITLE
flavours/glitch/reducers/compose.js: Fix toLowerCase TypeError

### PR DESCRIPTION
**Pull request by lanodan**
[Error] TypeError: e.toLowerCase is not a function. (In 'e.toLowerCase()', 'e.toLowerCase' is undefined)

Some added context: https://queer.hacktivis.me/notice/9g4OfhpIWQLNoZ3mLI

### CODE REVIEW

**Comment by lanodan** [comment]
Note: This is untested for now so more commits might come.

**Comment by ThibG** [comment]
> Note: This is untested for now so more commits might come.

Any update on this?

**Comment by lanodan** [comment]
[2019-03-05 10:21:31] ThibG:
> > Note: This is untested for now so more commits might come.
> 
> Any update on this?

yeah, I think I’ll need further debugging as it is still present
after this fix.

I’m not sure if WebKit properly erases LocalStorage with ephemeral
sessions but it does seems to be related.

**Comment by ThibG** [comment]
Haven't heard back and haven't encountered any issue with that codepath so far, so I'm gonna close this PR. Please reopen if needed.

**Pull request closed without merging**
