### PR TITLE
Allow keyword mutes to skip mentions (#454)

### PR DESCRIPTION
**Pull request by yipdw**
TODO:

- [x] Get #530 merged
- [X] Augment `glitch_keyword_mutes` with "should this apply to mentions" data
- [X] Scope matchers
- [x] Demonstrate that this works via the test suite
- [x] Add UI to toggle/show `apply_to_mentions`
- [x] If a post shows up in mentions, it should show up in the home feed also

### CODE REVIEW

**Comment by yipdw** [comment]
This was originally requested by @impiaaa and I'd like to solicit changes from them, as well as anyone else in @glitch-soc who might feel strongly about the changes shown above.

**Comment by impiaaa** [comment]
I don't have any feedback as I don't really use mutes.

**Comment by yipdw** [comment]
Oh, sorry.  I recall you bringing this up as a desired feature, but that recollection could be wrong.

**Comment by yipdw** [comment]
I think the only thing I'll change from this (unless someone else steps in with an idea) is to make a permitted toot show up both in notifications and the home feed.  That's probably doable with some finagling of `keyword_filter?` and IMO it is the expected behavior.

"Apply to mentions" is probably a bit confusing at first glance, but it reads fine to me and the cost of inverting its meaning is not high.

**Comment by yipdw** [comment]
The last sub-task for this PR has been completed.

**Pull request merged**
