### PR TITLE
fullwidth images

### PR DESCRIPTION
**Pull request by Chronister**
Makes all images / videos take up the whole width of the column and up to 30% of the viewport height, similar to Tweetdeck's large image mode.

### CODE REVIEW

**Comment by marrus-sh** [comment]
I've implemented most of these things internally as of ec2daae71ca03b414fa41a07e13e9653b0dff0a4; however, the `30vh` heights haven't been implemented. Right now, toot collapsing detection expects images to have a height of `250px`; it will take some work to get them to base this off of the viewport height instead. (Not impossible tho).

**Comment by beatrix-bitrot** [comment]
@marrus-sh the main thing i was interested in with this one is that i think @Chronister fixed the ordering of the thumbnails. are they still weird on the dev server?

**Comment by marrus-sh** [comment]
I believe they are not!

**Comment by nightpool** [comment]
does glitch-soc have custom code to generate the previews with? that's my
main concern with cybrespace right now—all of the previews are super blurry
and pixelated.

**Comment by marrus-sh** [comment]
We just use the default thumbnails provided by Mastodon, which, uh… i'm not sure how they're generated, exactly. But it's not anything custom afaik.

**Comment by nightpool** [comment]
Okay. They're generated by paperclip, but they're set up for the old
config. I want to fix it so that they're the right resolution for the full
width stuff

**Pull request closed without merging**
