### PR TITLE
Merge and port upstream's composer change

### LINKED ISSUE #2591: Glitch-soc web UI doesn't ask for media description when using Command/Control-Enter to send post
### Steps to reproduce the problem

1. Enable the following setting: "Show confirmation dialog before sending toots lacking media descriptions" (in App preferences > Compose box)
2. Attach an image or video
3. Send post by using the Command-Enter or Control-Enter shortcut
4. Experience Unexpected/Actual behavior

### Expected behaviour

Glitch-soc web UI asks for missing media description

### Actual behaviour

Glitch-soc web UI just sends the post

### Detailed description

To make the prompt show up, click the "Publish!" button with the mouse instead of using the send post keyboard shortcut.

### Mastodon instance

micro.jacksonchen666.com

### Mastodon version

v4.3.0-alpha.0+chuckya.jacksonchen666

### Browser name and version

LibreWolf 122.0-1

### Operating system

macOS 14.2.1

### Technical details

micro.jacksonchen666.com is my Glitch-soc-based instance, and was running on [2e1e909fa992be4d4984f4b9710d859c8f124f6e](https://git.sr.ht/~jacksonchen666/glitch-soc-mastodon-fork/commit/2e1e909fa992be4d4984f4b9710d859c8f124f6e) at the time of reproducing the bug.

[My very-soft-fork](https://git.sr.ht/~jacksonchen666/glitch-soc-mastodon-fork) is based on [wetdry.world's source code](https://github.com/TheEssem/mastodon), which is based on [glitch-soc](https://github.com/glitch-soc/mastodon), etc. etc. etc.

Source code for my instance can just be cloned:
```
git clone https://git.sr.ht/~jacksonchen666/glitch-soc-mastodon-fork
```

---

I have been able to reproduce this issue on catcatnya.com as well (`v4.3.0-alpha.0+glitch+cat+1.0.12`, https://github.com/CatCatNya/catstodon).

### PR DESCRIPTION
**Pull request by ClearlyClaire**
Fixes #2591

Unlike most changes, this will need to be ported straight away due to the widespread translation string changes.

image
image
image

## List of glitch-soc features that need to be reimplemented for the new design

- [x] glitch-soc settings in drawer tab bar
- [x] notification badge in drawer tab bar
- [x] configurable limits for characters and poll options
- [x] secondary post privacy
- [x] confirmation when posting media without description
- [x] always enable CW field (still some bugs)
- [x] prepend “re: ” in CW when replying
- [x] optionally pre-select usernames on reply
- [x] content-type choice
- [x] local-only posting
- [x] threaded mode
- [x] option to use native emoji font (relevant in picker)
- [x] `Link` vs `Permalink`
- [x] glitchy mascot
- [ ] doodle

### Conflicts

Conflicts:
- `app/javascript/mastodon/features/compose/components/compose_form.jsx`:
  Upstream completely redesigned this, and glitch-soc had different handling for the character limit.
  Ported upstream's change to the new version.
- `app/javascript/mastodon/features/compose/components/poll_form.jsx`:
  Upstream completely redesigned this, and glitch-soc had different limits for option length and number of options.
  Ported glitch-soc's changes to the new version.

Additional change:
- `app/javascript/styles/components.scss`:
  Change how the new image is looked up.

### Ported changes

- 9c10aaa4d5bed500c074c1bef3caaa1e84949c00

### Additional changes

A whole lot!

### CODE REVIEW

**Comment by ClearlyClaire** [comment]
kind of a mess but most of the functionality is back
image

**Comment by mkody** [comment]
Could the local-only setting be integrated with the Visibility options?
Similarly to how Sharkey recently implemented it when you try to boost a post: 
image

**Comment by ClearlyClaire** [comment]
> Could the local-only setting be integrated with the Visibility options? This could save up some space. Similarly to how Sharkey recently implemented it when you try to boost a post: image

That could make sense, but that would be more work, and also I'm afraid this would not be visually apparent enough once the option is closed?

**Comment by ClearlyClaire** [comment]
Some features are still missing, but they are kind of a pain to do…

**Pull request merged**
