### PR TITLE
merge upstream

### PR DESCRIPTION
**Pull request by beatrix-bitrot**
uhhhhhhhhhhhhhhhhh

### CODE REVIEW

**Comment by beatrix-bitrot** [comment]
i mostly created this PR to have a look and see what the conflicts would be. i guess it's all y'alls nice work on the front end

@marrus-sh @MightyPork do either (or both together somehow?) of y'all wanna take a crack at this?

i CAN but well you know... the outcome is by no means guaranteed to be good d:

**Comment by MightyPork** [comment]
rip

can we even do any kind of co-op attempt at this or one must do it all?

**Comment by beatrix-bitrot** [comment]
i'm honestly not sure... also wow it updates in realtime!

**Comment by marrus-sh** [comment]
I'm gonna move some files around and restructure the frontend a lil and then take a shot at merging this~

**Pull request merged**
