### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by ThibG**
A lot of upstream changes, the most disruptive being:
- Dropped support for OStatus and Atom feeds
- Added an anti-spam feature that auto-silences and auto-report remote accounts posting very similar (according to the Nilsimsa Hash algorithm) unsolicited (as in, mentioning at least one local user who do not follow them, and not in reply to a message mentioning them) messages. ~~It is currently *not* optional.~~ It can be disabled from the admin settings.
- Started signing every fetch with ~~the representative account (that is, the contact account if it is defined, the first non-suspended local account in the database otherwise)~~ a dedicated instance actor
- Added an option to disable reverse proxy caches and only serve toots if there is a valid signature (it is unadvisable to enable that option right now, as no Mastodon release currently signs queries)

### CODE REVIEW

**Comment by BenLubar** [comment]
> * Started signing every fetch with the representative account (that is, the contact account if it is defined, the first non-suspended local account in the database otherwise)

This may be a problem for followers-only posts.

What happens if a post is successfully fetched for the first time on behalf of the admin but a user wasn't supposed to see it? (I saw this happen with Peertube's unlisted videos.)

And if the admin doesn't follow someone, does that mean the post just won't get fetched successfully?

**Comment by ThibG** [comment]
> What happens if a post is successfully fetched for the first time on behalf of the admin but a user wasn't supposed to see it? (I saw this happen with Peertube's unlisted videos.)

Good question, you're right, this may be an issue, I'll investigate.

> And if the admin doesn't follow someone, does that mean the post just won't get fetched successfully?

Yes.

**Comment by ashkitten** [comment]
i thought this was supposed to be implemented with special instance actors, not reusing existing accounts?

**Comment by ThibG** [comment]
For the moment it's reusing existing accounts.

**Comment by ashkitten** [comment]
this will be a problem if i block the admin of another instance and another person on the instance tries to fetch an object from my account, yes? and federation with that instance will be broken entirely if i suspended that admin from the moderation console?

**Comment by ThibG** [comment]
> this will be a problem if i block the admin of another instance and another person on the instance tries to fetch an object from my account, yes? and federation with that instance will be broken entirely if i suspended that admin from the moderation console?

yes, if you block the admin, their instance won't be able to fetch toots for boosts etc.

**Comment by BenLubar** [comment]
> > this will be a problem if i block the admin of another instance and another person on the instance tries to fetch an object from my account, yes? and federation with that instance will be broken entirely if i suspended that admin from the moderation console?
> 
> yes, if you block the admin, their instance won't be able to fetch toots for boosts etc.

How hard would it be to have an arbitrary user that could see the post fetch it instead?

Like, if someone receives a boost, fetch as one of the people who received it. If someone searches for a URL, fetch it as that user. Fallback for stuff like relays can be the admin.

**Comment by BenLubar** [comment]
Gonna /cc @Gargron in this discussion because it's relevant for tootsuite as well.

**Comment by ashkitten** [comment]
feels like implementing this without proper instance actors is going to be difficult to cut out edge cases

**Comment by ThibG** [comment]
There is indeed a way private toots could be leaked, opened a PR for that: https://github.com/tootsuite/mastodon/pull/11300

> Like, if someone receives a boost, fetch as one of the people who received it. If someone searches for a URL, fetch it as that user. Fallback for stuff like relays can be the admin.

Actually, for boosts, we already fetch toots from a follower of the person boosting them (and that may already fail if that follower is blocked by the person being boosted)

**Comment by ashkitten** [comment]
i will say that from the start, malicious instances have been able to show statuses to the wrong users. this won't change that, we're only talking about preventing other instances as a whole from fetching things they otherwise shouldn't be able to access, as a whole. to that end, i think we should rely on the "special instance actor" from other discussions. here is how i envision it working:

1. instance A has a user steve who requests a followers-only status from user diane, whom he follows on instance B
2. instance A sends a request to instance B for that status, signed by the special instance actor for A
3. instance B knows that steve follows diane, therefore that status should be visible to instance A
4. instance B authorizes the fetch and sends A the status.
5. instance A receives the status and inserts it into its database
6. instance A checks that steve should be allowed to view the status and presents it to him

now say ida, another user on instance A wants to view the same status, but does not follow diane:

1. ida requests the status
2. instance A sends a request to instance B for that status, signed by the special instance actor for A
3. instance B knows that steve follows diane, therefore that status should be visible to instance A
4. instance B authorizes the fetch and sends A the status.
5. instance A receives the status and inserts it into its database
6. instance A checks that ida should be allowed to view the status. since she does not follow diane, she is presented with an error

now what happens when a user from instance C tries to fetch the status?

1. greg from instance C tries to fetch the status
2. instance C sends a request to instance B for that status, signed by the special instance actor for C
3. instance B sees that nobody on instance C is authorized to view the status, so it does not authorize the fetch
4. greg is presented with an error

**Comment by cwebber** [comment]
I'll say that I'm nervous about the edge case'y nature that it sounds like this is going to introduce.

I need to get my alternative proposal written up but I'm worried that we're going to see behavior merged that breaks the underlying paradigm and ultimately results in a lot of broken stuff soon. :(

**Comment by cwebber** [comment]
I'm very, very worried about what will happen if this becomes merged and pushed out across the fediverse.  I know people are applying the paradigms they know, but this is the wrong security paradigm.  We might go down a course we can never get back from by taking the "who is calling me" approach.

Please allow me time this week to write up a document explaining why along with an alternative approach before merging this.

**Comment by ThibG** [comment]
All of this is already in upstream (but not in any release).

I am unsure how the approach of this PR is different from the one we already have for *posting* toots. The main issue is that we want to fetch on behalf of “all” users and not a specific one. We've already been handling authenticated fetches for a while in Mastodon, but neither required them nor heavily relied on them (actually, we only relied on them for self-boosts for a short while but do not anymore).

For the purpose of consenting to an user (or instance) viewing a toot, I fail to see what this PR doesn't cover (although it requires signing, verifying and occasionally fetching keys, which is not ideal). I fail to see how it *contradicts* other approaches.

That being said, I am not interested in pushing a solution if a different, better one is just around the corner, and even if we were going to follow upstream's approach, there are still things needing to be ironed out, so we will definitely hold off from merging it in glitch-soc for the time being.

**Comment by BenLubar** [comment]
The main thing I'm worried about is admins that follow someone causing followers-only posts that haven't arrived yet to be visible when they're force-fetched.

**Comment by Gargron** [comment]
@BenLubar That has been fixed upstream thanks to @ThibG.

@cwebber The "who is calling me" approach you are describing is the basis of all API authentication (API keys) as well as all website logins (username/password, session cookie) in the world. I am very confused why you think this is different. We've been authenticating inbox deliveries using this approach since the start of ActivityPub.

**Comment by TemporaryUsername12481** [comment]
> Started signing every fetch with the representative account (that is, the contact account if it is defined, the first non-suspended local account in the database otherwise)

Shouldn't fetches be signed with the user who initiated it (either the user who manually searched for the object, or the user whose inbox received the `Announce` object)?

**Comment by ThibG** [comment]
> > Started signing every fetch with the representative account (that is, the contact account if it is defined, the first non-suspended local account in the database otherwise)
> 
> Shouldn't fetches be signed with the user who initiated it (either the user who manually searched for the object, or the user whose inbox received the `Announce` object)?

We want to avoid leaking info about user action as much as possible, so no. Also, we are doing something similar for `Announce` but we might want to stop doing that, for various reasons, one of which being that out of all followers of the person boosting the toot, we can't really know which might be blocked by the person being boosted. As soon as we have an instance actor, we might want to use that.

**Comment by cwebber** [comment]
> @cwebber The "who is calling me" approach you are describing is the basis of all API authentication (API keys) as well as all website logins (username/password, session cookie) in the world. I am very confused why you think this is different. We've been authenticating inbox deliveries using this approach since the start of ActivityPub.

There's the source of misunderstanding: I'm saying that "who is calling me" is a broken model.  "Who said this thing" is another thing entirely; that's verifying the authenticity of messages.  Authentication != authorization, though I know that prevailing paradigms conflate the two.  You can see oauth bearer tokens, for instance, as authority without authorization (even if authorization was used to obtain them, and it isn't always).

That's the problem: a move from authentication to verify who is saying things to authentication as a form of authorization.  I know it isn't obvious that this is a risk, and while there is academic'ish literature out there that explains it, I need to distill what risks we are facing here for an AP-implementor audience (we've done a bit more to explain the general concepts in [this episode of Libre Lounge](https://librelounge.org/episodes/episode-13-object-capabilities-with-kate-sills.html) but it isn't "targeted" at the risks to moving to this model for authorization on the fediverse specifically).

Anyway, I'm off to write.

**Comment by ThibG** [comment]
Upstream now signs fetch requests with a dedicated actor not representing an user in particular, and the anti-spam can be disabled from the admin interface.

Therefore, I am ready to merge this into glitch-soc.

The code for requiring authentication for fetches is here and can be enabled, but its use is not encouraged nor documented. I don't think having it in changes anything wrt. our ability to switch to an ocap-based approach when that starts being sufficiently well specified.

**Pull request merged**
