### PR TITLE
Add new filtering behaviors to glitch-soc flavour

### PR DESCRIPTION
**Pull request by ThibG**
image

image

image

TODO:
- ~~refactor spoiler-like behavior component~~
- ~~use i18n for new option strings~~

EDITED: changed how the “show why” button is displayed:
image

### CODE REVIEW

**Comment by BenLubar** [comment]
could the "show why" link be on the same line as "Filtered"?

could the "show why" modal give a way to view the post?

**Comment by ThibG** [comment]
> could the "show why" link be on the same line as "Filtered"?

Yes, it could, I will try doing that (I tried being more consistent with the links used in vanilla Mastodon to unfold long posts and things like that, but it does not make that much sense since we don't use them ourselves)

> could the "show why" modal give a way to view the post?

I'm not sure I understand the purpose of that, since viewing the post is done by clicking the “show” button?

**Comment by ThibG** [comment]
@BenLubar would that be better? 
image

**Comment by ThibG** [comment]
Cleaned up, put the “show why” button alongside the “Filter” text, and also added a link to the filter edition interface for every matching filter:
image

**Pull request merged**
