### PR TITLE
Add "unsafe-wasm-eval" to script-src CSP

### PR DESCRIPTION
**Pull request by prplecake**
Ports mastodon/mastodon#18817 to glitch.

> Firefox now supports Content-Security-Policy (CSP) integration with WebAssembly. A document with a CSP that restricts scripts will no longer execute WebAssembly unless the policy uses 'unsafe-eval' or the new 'wasm-unsafe-eval' keyword."

https://connect.mozilla.org/t5/discussions/new-csp-enhancements-in-firefox-102/td-p/8816

### CODE REVIEW

**Comment by prplecake** [comment]
Merged from upstream in #1876

**Comment by ClearlyClaire** [comment]
Sorry for the confusion, but I specifically did not merge that part when merging the upstream changes. I'm still not sure what's the best course of action would be, I'm a bit uncomfortable with something as wide as unsafe-eval

**Comment by prplecake** [comment]
Can't wait to see what you come up with. I couldn't get it to work with anything stricter.

**Comment by prplecake** [comment]
I blame ruby for this whole fuckery, apparently 'unsafe-wasm-eval' works if you quote it right... see mastodon#18817

**Pull request closed without merging**
