### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by yipdw**
Conflicts:
* `app/javascript/mastodon/locales/en.json`
* `app/javascript/mastodon/locales/ja.json`
* `app/javascript/mastodon/locales/pl.json`
    
The above conflicts appear to be a text conflict introduced by glitch-soc's additional level of columns (i.e. moving a bunch of columns under the Misc option).  They were resolved via accept-ours.

### CODE REVIEW

**Comment by yipdw** [comment]
Grr: https://travis-ci.org/glitch-soc/mastodon/jobs/387223977

Is this a webpack timeout?

**Comment by rhaamo** [comment]
There is an error line 1800, can it be that issue ? it touch one of the conflicted file:
```
ERROR in ./app/javascript/mastodon/locales/ja.json
Module build failed: SyntaxError: Unexpected token < in JSON at position 7738
    at Object.parse (native)
    at Object.module.exports (/home/travis/build/glitch-soc/mastodon/node_modules/json-loader/index.js:4:49)
 @ ./tmp/locales/vanilla/ja.js 6:0-72
```

**Comment by rhaamo** [comment]
@yipdw if I look at "Files Changed" I see a:
image

Forgot deconflicting this file ?

**Comment by yipdw** [comment]
Damnit.  I thought I got that.

**Pull request merged**
