### PR TITLE
Port the “unfold thread” feature from Mastodon's UI to glitch-soc flavour

### LINKED ISSUE #387: Port “Add show more/less toggle for entire threads in web UI”
This was implemented in b6003afcdb1b89eb967a2b211e3b4e26aed9ac9d for Mastodon, and it would be nice to have in glitch-soc.

However, glitch-soc and Mastodon have diverged quite a bit in this part of the code, most notably because of glitch-soc's collapsable toots.

### PR DESCRIPTION
**Pull request by ThibG**
This is a very much in progress PR aiming to implement he “unfold thread” feature of Mastodon (fixes #387). Unfortunately, as the code has diverged quite a bit and is pretty hard to reason about, it will take some work.

- [x] Port related changes to column headers
- [x] Refactor the collapsed/extended logic to make it easier to reason about
- [x] Port the feature itself

~~~It is still work in progress as the interaction between CWs and collapsed toots is not satisfactory.~~~

### CODE REVIEW

**Comment by ThibG** [comment]
Porting this feature really is a pain, in terms of user interface, because of collapsed toots. The crux of the problem is the following:
1. This change makes the folded/unfolded status for content warnings shared across every view of a toot
2. So far, the collapsed/not-collapsed state of a toot is specific to a view of a toot. It makes sense because one may want toots in their notifications column collapsed while not having them collapsed in their TL
3. It does not make much sense for a collapsed toot to have have its content warning unfolded, especially as that would cause the “fold/unfold” button to not have seemingly no effect on collapsed toots

In the current state of this PR, point 3 is ignored, and the “CW unfolded but collapsed view” state is possible, which is a regression.
I'm not too sure how to proceed, but I'm considering changing 1 to keep the previous behavior, but it will be more work and it will not bring Mastodon and glitch-soc codebases closer…

**Comment by marrus-sh** [comment]
Yeah I am not a fan of having CW folding status shared across every instance of the toot for a number of reasons:

1. In notifications it makes things really awful if you have a bunch of notifications on the same, CW'd toot, and then you expand it (all of the instances of the toot in the notifications bar expand)
2. In general, I think rendering details should be kept out of redux (this is a personal stance which upstream does not share) and that the redux store should be reserved just for API stuff

I think upstream's approach to this was kinda hacky and not great from a useability perspective and results (imho) from an overreliance on Redux as a catch-all solution to every problem, which it isn't :P. Instead this should be handled via a passed prop/state from the conversation column (React idiomatic if a little complicated) or via Events (the better, cleaner solution, but not in line with any of the existing codebase).

**Comment by ThibG** [comment]
Alright, this is something I wasn't too sure about. I'll try to rework the PR to fold/unfold the toots in the thread view only, not using the Redux store for that.

**Comment by ThibG** [comment]
Updated to not use redux. The CW fold/unfold state is now specific to each view of the toot, unlike in tootsuite/mastodon. Tried to keep the differences with tootsuite/mastodon minimal nevertheless.

**Pull request merged**
